/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  FruityEdit as FruityEdit
} from './components/fruity-edit/fruity-edit';

declare global {
  interface HTMLFruityEditElement extends FruityEdit, HTMLElement {
  }
  var HTMLFruityEditElement: {
    prototype: HTMLFruityEditElement;
    new (): HTMLFruityEditElement;
  };
  interface HTMLElementTagNameMap {
    "fruity-edit": HTMLFruityEditElement;
  }
  interface ElementTagNameMap {
    "fruity-edit": HTMLFruityEditElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "fruity-edit": JSXElements.FruityEditAttributes;
    }
  }
  namespace JSXElements {
    export interface FruityEditAttributes extends HTMLAttributes {
      match?: any;
    }
  }
}

