/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  FruityCms as FruityCms
} from './components/fruity-cms/fruity-cms';

declare global {
  interface HTMLFruityCmsElement extends FruityCms, HTMLElement {
  }
  var HTMLFruityCmsElement: {
    prototype: HTMLFruityCmsElement;
    new (): HTMLFruityCmsElement;
  };
  interface HTMLElementTagNameMap {
    "fruity-cms": HTMLFruityCmsElement;
  }
  interface ElementTagNameMap {
    "fruity-cms": HTMLFruityCmsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "fruity-cms": JSXElements.FruityCmsAttributes;
    }
  }
  namespace JSXElements {
    export interface FruityCmsAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  FruityHeader as FruityHeader
} from './components/fruity-header/fruity-header';

declare global {
  interface HTMLFruityHeaderElement extends FruityHeader, HTMLElement {
  }
  var HTMLFruityHeaderElement: {
    prototype: HTMLFruityHeaderElement;
    new (): HTMLFruityHeaderElement;
  };
  interface HTMLElementTagNameMap {
    "fruity-header": HTMLFruityHeaderElement;
  }
  interface ElementTagNameMap {
    "fruity-header": HTMLFruityHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "fruity-header": JSXElements.FruityHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface FruityHeaderAttributes extends HTMLAttributes {
      cmsName?: string;
      navigation?: object;
    }
  }
}


import {
  FruityHome as FruityHome
} from './components/fruity-home/fruity-home';

declare global {
  interface HTMLFruityHomeElement extends FruityHome, HTMLElement {
  }
  var HTMLFruityHomeElement: {
    prototype: HTMLFruityHomeElement;
    new (): HTMLFruityHomeElement;
  };
  interface HTMLElementTagNameMap {
    "fruity-home": HTMLFruityHomeElement;
  }
  interface ElementTagNameMap {
    "fruity-home": HTMLFruityHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "fruity-home": JSXElements.FruityHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface FruityHomeAttributes extends HTMLAttributes {
      
    }
  }
}

